server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.09:3306/maple_forest_sys?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Arvin@01

mybatis:
  mapper-locations: classpath:com/arvin/mapleforestbackend/mapper/*.xml
  type-aliases-package: com.arvin.mapleforestbackend.POJO